[2025-10-18T22:44:48.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-18T22:44:48.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1.load_data_task scheduled__2025-10-17T00:00:00+00:00 [queued]>
[2025-10-18T22:44:48.135+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1.load_data_task scheduled__2025-10-17T00:00:00+00:00 [queued]>
[2025-10-18T22:44:48.135+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-18T22:44:48.141+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_task> on 2025-10-17 00:00:00+00:00
[2025-10-18T22:44:48.149+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-18T22:44:48.151+0000] {standard_task_runner.py:63} INFO - Started process 93 to run task
[2025-10-18T22:44:48.150+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_data_task', 'scheduled__2025-10-17T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/***1.py', '--cfg-path', '/tmp/tmp1xt1d681']
[2025-10-18T22:44:48.153+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask load_data_task
[2025-10-18T22:44:48.184+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1.load_data_task scheduled__2025-10-17T00:00:00+00:00 [running]> on host e52b226bd96e
[2025-10-18T22:44:48.227+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-17T00:00:00+00:00'
[2025-10-18T22:44:48.228+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-18T22:44:48.243+0000] {logging_mixin.py:188} INFO - We are here
[2025-10-18T22:44:48.245+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-18T22:44:48.245+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/lab.py", line 16, in load_data
    df = pd.read_csv(os.path.join(os.path.dirname(__file__), "../data/file.csv"))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/src/../data/file.csv'
[2025-10-18T22:44:48.252+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab1, task_id=load_data_task, run_id=scheduled__2025-10-17T00:00:00+00:00, execution_date=20251017T000000, start_date=20251018T224448, end_date=20251018T224448
[2025-10-18T22:44:48.259+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task load_data_task ([Errno 2] No such file or directory: '/opt/airflow/dags/src/../data/file.csv'; 93)
[2025-10-18T22:44:48.290+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-18T22:44:48.302+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-18T22:44:48.303+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
